name: ProxyTransport Release

on:
  push:
    branches: [ master, feature/autobuild ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: microsoft
      - name: "Print env variables"
        run: env

      - name: Build ProxyTransport
        run: mvn -B install --file pom.xml
      - name: Create and Publish Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          body: ""
          tag: "${GITHUB_REF#refs/heads/}"
          name: "${{ github.event.head_commit.message }}"
          artifacts: "target/proxy-transport-1.0.jar"
