name: ProxyTransport Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: microsoft
      - name: Build ProxyTransport
        run: mvn -B install -q --file pom.xml
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Release ${{ github.ref }} by ${{ github.actor }}"
          files: |
            target/ProxyTransport.jar