name: Publish package to the Maven Repository
on:
  push:
    branches: ['master']
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish client
        run: mvn -T 4 --batch-mode deploy -q -s settings.xml
        env:
          REPO_USERNAME: github-deploy
          REPO_PASSWORD: ${{ secrets.DEPLOY_TOKEN }}