name: Publish package
on:
  push:
    branches: ['master']
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.5.0
        with:
          java-version: '17'
          java-distribution: 'adopt'
      - name: Publish and package client
        run: mvn -T 4 --batch-mode deploy package -q -s settings.xml
        env:
          REPO_USERNAME: github-deploy
          REPO_PASSWORD: ${{ secrets.DEPLOY_TOKEN }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ProxyTransport
          path: target/ProxyTransport.jar